# Generated by Django 2.2.12 on 2020-05-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_remove_produto_importado'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ncm',
            field=models.CharField(default='0', max_length=8, verbose_name='NCM'),
        ),
    ]
