# Generated by Django 2.2.12 on 2020-06-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_produto_ncm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.PositiveIntegerField(verbose_name='estoque atual'),
        ),
    ]
