# Generated by Django 2.2.12 on 2020-06-24 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_auto_20200623_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='data_entrada',
            field=models.DateField(default=datetime.datetime(2020, 6, 23, 21, 49, 49, 701371), null=True),
        ),
    ]
